### ISSUE TITLE
Help with setup of customised Magento2 build

### ISSUE THREAD

**Issue by WinstonN** [ModestCoders/magento2-dockergento#43]
Hi Hi, 

I am looking to use dockergento (I love it so much) on my current project, but the setup is a little different
I run a mac now - not sure if this info would help
Essentially everything is in a directory called **src**

When I run 
```
dockergento setup
```

I specify the paths, which results in this config properties file
(I did specify all paths as **./src/** but only the bin dir kept the **./**) 
```
MAGENTO_DIR="src"
COMPOSER_DIR="src/vendor"
BIN_DIR="./src/vendor/bin"
```

However, on the first start I get this error message
```
➜ dockergento start
Starting containers in detached mode
Starting magento2_db_1 ... done
Creating magento2_phpfpm_1 ... done
Creating magento2_nginx_1  ... done

Vendor cannot be a bind mount. Please do the following:

  1. Remove from your docker-compose configuration:
      - ./<host_path>:/var/www/html/src/vendor/composer.lock

  2. Execute:
      dockergento rebuild
```
After doing those steps, dockergento starts up fine, but the container, seems to miss almost all of the files

It only contains
```
➜ dockergento bash
app@b60e9463a17c:~/html$ ls -la
total 668
drwxr-xr-x 5 app app   4096 Apr  3 08:20 .
drwxr-xr-x 5 app app   4096 Apr  3 08:20 ..
drwxr-xr-x 2 app app     64 Mar 18 08:48 .git
drwxr-xr-x 9 app app    288 Apr  2 19:40 app
-rw-r--r-- 1 app app  10432 Apr  2 22:31 composer.json
-rw-r--r-- 1 app app 661650 Apr  2 22:31 composer.lock
drwxr-xr-x 3 app app     96 Apr  3 08:20 config
``` 

I thought I could copy the files over with
```
➜ dockergento mirror-host src/ /var/www/html/src/
```

But this gives me an error, forcing me to copy directory by directory
Which also doesn't work

Essentially, I never get to a working site

Here is my docker-compose.dev.mac.yml file
```
version: "3"

services:
  phpfpm:
    volumes: &appvolumes-mac
      - ../.composer:/var/www/.composer:delegated
      - workspace:/var/www/html
      - ./src/app:/var/www/html/src/app:delegated
      - ./.git:/var/www/html/.git:delegated
      - ./config:/var/www/html/config:delegated
      - ./.circleci:/var/www/html/.circleci:delegated
      - ./.gitignore:/var/www/html/.gitignore:delegated
      - ./CHANGELOG.md:/var/www/html/CHANGELOG.md:delegated
      - ./README.md:/var/www/html/README.md:delegated
      - ./ami:/var/www/html/ami:delegated
      - ./appspec.yml:/var/www/html/appspec.yml:delegated
      - ./docs:/var/www/html/docs:delegated
      - ./env:/var/www/html/env:delegated

  nginx:
    volumes: *appvolumes-mac

  node:
    volumes: *appvolumes-mac

  unison:
    image: modestcoders/unison:2.51.2
    volumes:
      - workspace:/var/www/html
      - ./src/vendor:/sync/src/vendor
    environment:
      - SYNC_SOURCE_BASE_PATH=/sync
      - SYNC_DESTINATION_BASE_PATH=/var/www/html
      - SYNC_MAX_INOTIFY_WATCHES=60000
    depends_on:
      - phpfpm
    privileged: true

volumes:
  workspace:

```

How can I fix this?
